### ISSUE TITLE
Fix vulnerability issues

### ISSUE THREAD

**Issue by fvoska** [infinum/ngx-nuts-and-bolts#15]
Check the issues that dependabot is reporting. Also run `npm audit` and fix any issues that might be reported there.

**Comment by DarkoKukovec** [comment]
Maybe also add dependabot for deps updates? he.g. ttps://github.com/infinum/datx/blob/master/.github/dependabot.yml

**Comment by fvoska** [comment]
Dependabot added and some issues fixed. Closing this issue and we will regularly check dependabot reports
