### ISSUE TITLE
Helpers for working with tables

### ISSUE THREAD

**Issue by JosipJanus** [infinum/ngx-nuts-and-bolts#32]
### Discussed in https://github.com/infinum/ngx-nuts-and-bolts/discussions/12

<div type='discussions-op-text'>

<sup>Originally posted by **fvoska** January 19, 2022</sup>
Implement helpers for working with tables that store state in query parameters and can be used for reactive development of tables.

@JosipJanus will work on this.</div>

**Comment by fvoska** [comment]
Closed via https://github.com/infinum/ngx-nuts-and-bolts/pull/31
