### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by JosipJanus** [infinum/ngx-nuts-and-bolts#35]
### Discussed in https://github.com/infinum/ngx-nuts-and-bolts/discussions/14

<div type='discussions-op-text'>

<sup>Originally posted by **fvoska** January 19, 2022</sup>
Instead of having plain markdown files, investigate options building a website form the markdown files with versioning support and some basic information / landing page.

[Docusaurus](https://docusaurus.io/) seems like a good option and we already use it for [@datx](https://github.com/infinum/datx/tree/master/website) and [ngx-form-object](https://github.com/infinum/ngx-form-object/tree/master/docusaurus).

Our project uses Nx, so [this](https://github.com/ZachJW34/nx-plus/tree/master/libs/docusaurus) plugin might be convenient. My worry is that the plugin might stop being maintained and might block us from upgrading Nx Workspace.

@JosipJanus will investigate this</div>

**Comment by fvoska** [comment]
Closed via #41
