### ISSUE TITLE
Add tooltip directive with support for custom template

### ISSUE THREAD

**Issue by danipavic** [infinum/ngx-nuts-and-bolts#89]
Description
Add a tooltip directive that will enable a user to load an Angular template with a custom HTML. Ordinary mat-tooltip is only supporting text, so when a tooltip needs custom markup and styling, mat-tooltip is not enough.

API proposal
A standalone directive that can be attached to a trigger element and accepts a template as an input, which is then loaded when the user hovers over the host element. 

The directive would attach a mouseEnter/mouseOver handler to the host element that will toggle the tooltip.

The directive selector should have a matching `@Input()` that will be used for passing the `templateRef`.

```
<div [infTooltip]="tooltipTemplate">
 Hover!
</div>

<section #tooltipTemplate>
  ...
</section>
```

**Comment by Erbenos** [comment]
Think we should rather advice folk to use the [@ng](https://github.com/ngneat/helipopper) than do our own tooltip implementation. In simplest of cases `[title]` tooltip should perhaps suffice?

**Comment by danipavic** [comment]
I have tried Helipopper on my latest project and while it has some quirky/undocumented steps of setup it seems like a good out-of-the-box solution for tooltips so I don't think there is a need for custom implementation.
