### ISSUE TITLE
Animations should not animate non-animatable properties

### ISSUE THREAD

**Issue by fvoska** [infinum/ngx-nuts-and-bolts#98]
**Describe the bug**

The following console warning is present when using height animation:

`The animation trigger "height" is attempting to animate the following not animatable properties: display`

**Expected behaviour**

Non-animatable properties should not be animated and there should be no console warning.

**Comment by JosipJanus** [comment]
Do you remember where/when has this issue become apparent ? @fvoska

**Comment by fvoska** [comment]
I now notice that this was fixed via #99 ([this](https://github.com/infinum/ngx-nuts-and-bolts/pull/99/files#diff-0e9cc6272dedb178811fea086f1cf9aeba776838622b55eb0a0f0f0d3278558dL23) change)
